/**
 * SYNTHETIC test fixture for the search engine tests.
 *
 * These records are made up for tests and exist only in this folder: the
 * ids start with "SYN", the coordinates are arbitrary, and the weights are
 * picked to make ranking checks readable. Nothing here is imported by app
 * code or shipped.
 */
import type { SearchRecord } from '../types';

function school(
  id: string,
  name: string,
  sub: string,
  state: string,
  weight: number,
  lat = 40,
  lon = -76,
): SearchRecord {
  return { kind: 'school', id: `SYN${id}`, name, sub, state, lat, lon, weight };
}

export const SYNTHETIC_RECORDS: readonly SearchRecord[] = [
  // Schools and districts.
  school('S01', 'Lancaster High School', 'Lancaster, OH', 'OH', 1800, 39.71, -82.6),
  school('S02', 'Lancaster Mennonite School', 'Lancaster, PA', 'PA', 1400, 40.04, -76.25),
  school('S03', 'McCaskey Campus', 'Lancaster, PA', 'PA', 2500, 40.05, -76.29),
  school('S04', 'Lancasterville Elementary School', 'Dover, DE', 'DE', 300),
  school('S05', 'Hans Herr El Sch', 'Lancaster, PA', 'PA', 600),
  school('S06', 'Lincoln HS', 'Philadelphia, PA', 'PA', 900),
  school('S07', 'Lincoln High School', 'Des Moines, IA', 'IA', 1500),
  school('S08', 'Lincoln Elem', 'Omaha, NE', 'NE', 400),
  school('S09', "St. Mary's School", 'Albany, NY', 'NY', 250),
  school('S10', 'Saint Marys Academy', 'Portland, OR', 'OR', 350),
  school('S11', 'Cañon City High School', 'Cañon City, CO', 'CO', 800),
  school('S12', 'Española Valley High School', 'Española, NM', 'NM', 700),
  school('S13', "O'Neill Middle School", "O'Neill, NE", 'NE', 300),
  school('S14', 'P.S. 123 Mahalia Jackson', 'New York, NY', 'NY', 500),
  school('S15', 'Washington Park Elementary School', 'Washington, PA', 'PA', 320),
  school('S16', 'Riverside Elementary School', 'Springfield, IL', 'IL', 450),
  school('S17', 'Springfield High School', 'Springfield, IL', 'IL', 1600),
  school('S18', 'Jackson Middle School', 'Portland, OR', 'OR', 650),
  school('S19', 'Mt. Vernon Intermediate School', 'Mount Vernon, WA', 'WA', 550),
  school('S20', 'Arts & Sciences Academy', 'Boston, MA', 'MA', 300),
  school('S21', 'Oak Hill Elementary School', 'Lancaster, OH', 'OH', 410),
  school('S22', 'Oak Hill Elementary School', 'Fairfax, VA', 'VA', 410),
  school('S23', 'Oak Hill Elementary School', 'Austin, TX', 'TX', 410),
  {
    kind: 'district',
    id: 'SYND1',
    name: 'School District of Lancaster',
    sub: 'Lancaster, PA',
    state: 'PA',
    lat: 40.03,
    lon: -76.3,
    weight: 11000,
  },
  {
    kind: 'district',
    id: 'SYND2',
    name: 'Springfield SD 186',
    sub: 'Springfield, IL',
    state: 'IL',
    lat: 39.76,
    lon: -89.64,
    weight: 13000,
  },
  {
    kind: 'district',
    id: 'SYND3',
    name: 'Lancaster ISD',
    sub: 'Lancaster, TX',
    state: 'TX',
    lat: 32.59,
    lon: -96.76,
    weight: 7000,
  },
  // Cities.
  {
    kind: 'city',
    id: 'SYNC01',
    name: 'Lancaster',
    sub: 'Pennsylvania',
    state: 'PA',
    lat: 40.04,
    lon: -76.3,
    weight: 58000,
  },
  {
    kind: 'city',
    id: 'SYNC02',
    name: 'Lancaster',
    sub: 'California',
    state: 'CA',
    lat: 34.69,
    lon: -118.18,
    weight: 170000,
  },
  {
    kind: 'city',
    id: 'SYNC03',
    name: 'Lancaster',
    sub: 'Ohio',
    state: 'OH',
    lat: 39.73,
    lon: -82.61,
    weight: 40000,
  },
  {
    kind: 'city',
    id: 'SYNC04',
    name: 'Lancaster',
    sub: 'Texas',
    state: 'TX',
    lat: 32.6,
    lon: -96.77,
    weight: 41000,
  },
  {
    kind: 'city',
    id: 'SYNC05',
    name: 'New Lancaster',
    sub: 'Kansas',
    state: 'KS',
    lat: 38,
    lon: -95,
    weight: 90,
  },
  {
    kind: 'city',
    id: 'SYNC06',
    name: 'Springfield',
    sub: 'Illinois',
    state: 'IL',
    lat: 39.79,
    lon: -89.64,
    weight: 114000,
  },
  {
    kind: 'city',
    id: 'SYNC07',
    name: 'Springfield',
    sub: 'Massachusetts',
    state: 'MA',
    lat: 42.1,
    lon: -72.54,
    weight: 155000,
  },
  {
    kind: 'city',
    id: 'SYNC08',
    name: 'New York',
    sub: 'New York',
    state: 'NY',
    lat: 40.66,
    lon: -73.94,
    weight: 8300000,
  },
  {
    kind: 'city',
    id: 'SYNC09',
    name: 'New York Mills',
    sub: 'Minnesota',
    state: 'MN',
    lat: 46.5,
    lon: -95.4,
    weight: 1200,
  },
  {
    kind: 'city',
    id: 'SYNC10',
    name: 'Washington',
    sub: 'Pennsylvania',
    state: 'PA',
    lat: 40.17,
    lon: -80.25,
    weight: 13000,
  },
  {
    kind: 'city',
    id: 'SYNC11',
    name: 'Washington Park',
    sub: 'Illinois',
    state: 'IL',
    lat: 38.63,
    lon: -90.09,
    weight: 3000,
  },
  {
    kind: 'city',
    id: 'SYNC12',
    name: 'Cañon City',
    sub: 'Colorado',
    state: 'CO',
    lat: 38.44,
    lon: -105.22,
    weight: 17000,
  },
  {
    kind: 'city',
    id: 'SYNC13',
    name: 'St. Marys',
    sub: 'Pennsylvania',
    state: 'PA',
    lat: 41.45,
    lon: -78.52,
    weight: 12000,
  },
  {
    kind: 'city',
    id: 'SYNC14',
    name: 'Portland',
    sub: 'Oregon',
    state: 'OR',
    lat: 45.54,
    lon: -122.65,
    weight: 650000,
  },
  {
    kind: 'city',
    id: 'SYNC15',
    name: 'Portland',
    sub: 'Maine',
    state: 'ME',
    lat: 43.66,
    lon: -70.26,
    weight: 68000,
  },
  {
    kind: 'city',
    id: 'SYNC16',
    name: 'Orlando',
    sub: 'Florida',
    state: 'FL',
    lat: 28.47,
    lon: -81.32,
    weight: 300000,
  },
  {
    kind: 'city',
    id: 'SYNC17',
    name: 'Jackson',
    sub: 'Mississippi',
    state: 'MS',
    lat: 32.3,
    lon: -90.2,
    weight: 150000,
  },
  {
    kind: 'city',
    id: 'SYNC18',
    name: 'Pittsburgh',
    sub: 'Pennsylvania',
    state: 'PA',
    lat: 40.44,
    lon: -79.98,
    weight: 300000,
  },
  {
    kind: 'city',
    id: 'SYNC19',
    name: 'Philadelphia',
    sub: 'Pennsylvania',
    state: 'PA',
    lat: 40.0,
    lon: -75.13,
    weight: 1600000,
  },
  {
    kind: 'city',
    id: 'SYNC20',
    name: 'Unweighted Place',
    sub: 'Ohio',
    state: 'OH',
    lat: 40,
    lon: -83,
    weight: 0,
  },
  // ZIP codes.
  {
    kind: 'zip',
    id: '17601',
    name: '17601',
    sub: 'Pennsylvania',
    state: 'PA',
    lat: 40.07,
    lon: -76.31,
    weight: 0,
  },
  {
    kind: 'zip',
    id: '17602',
    name: '17602',
    sub: 'Pennsylvania',
    state: 'PA',
    lat: 40.01,
    lon: -76.25,
    weight: 0,
  },
  {
    kind: 'zip',
    id: '17603',
    name: '17603',
    sub: 'Pennsylvania',
    state: 'PA',
    lat: 40.03,
    lon: -76.33,
    weight: 0,
  },
  {
    kind: 'zip',
    id: '17701',
    name: '17701',
    sub: 'Pennsylvania',
    state: 'PA',
    lat: 41.24,
    lon: -77.0,
    weight: 0,
  },
  {
    kind: 'zip',
    id: '01002',
    name: '01002',
    sub: 'Massachusetts',
    state: 'MA',
    lat: 42.38,
    lon: -72.46,
    weight: 0,
  },
  {
    kind: 'zip',
    id: '12303',
    name: '12303',
    sub: 'New York',
    state: 'NY',
    lat: 42.76,
    lon: -73.93,
    weight: 0,
  },
];
