// Generated by scripts/build-us-mask.mjs. Do not edit by hand: run
// "npm run build:mask".

/** The US mask archive (mask/format.ts), relative to the site base URL. */
export const US_MASK_FILE = 'geo/us-mask.f212d993fb.pmtiles';

/** Its size in bytes, and the tiles it addresses. */
export const US_MASK_BYTES = 971228;
export const US_MASK_TILES = 8503;

/** The zooms it holds tiles for; deeper tiles take their ancestor's shape. */
export const US_MASK_MIN_ZOOM = 7;
export const US_MASK_MAX_ZOOM = 12;

/** What it was built from. */
export const US_MASK_SOURCES = [
  {
    publisher: 'U.S. Census Bureau',
    vintage: 'TIGER/Line Shapefiles 2025, States (published 2025-09-23)',
    url: 'https://www2.census.gov/geo/tiger/TIGER2025/STATE/tl_2025_us_state.zip',
    sha256: '59a220888a8d9be8117c4fcd38f542bd02d81abf0d198c78113595ad540dd957',
  },
  {
    publisher: 'International Boundary Commission',
    vintage: 'US-Canada boundary shapefile, version 1.3 (2018)',
    url: 'https://www.internationalboundarycommission.org/uploads/shapefile/us-canada-boundary-v1-3.zip',
    sha256: 'eb327459528b87cbc27e55ccc6bfd6982562c75559823a00b6dc50c04abcaab1',
  },
  {
    publisher: 'U.S. Census Bureau and International Boundary and Water Commission',
    vintage:
      'TIGER/Line Shapefiles 2025, International Boundary (US-Mexico section from the IBWC; published 2025-09-23)',
    url: 'https://www2.census.gov/geo/tiger/TIGER2025/INTERNATIONALBOUNDARY/tl_2025_us_internationalboundary.zip',
    sha256: '8da3c40ae83160178e979c59b26860af39f0c4bc11afa4e9d868785437ecac8e',
  },
] as const;
