"""Benchmark the name matcher: index build and matching time, precision and recall.

Run from ``pipeline/``::

    uv run python tests/match/bench_match.py
    uv run python tests/match/bench_match.py --directory out/internal/directory

The first form uses a SYNTHETIC directory of about 130,000 records generated by
:mod:`match.synthetic` and 1,000 labelled listings, then sweeps the acceptance
threshold over the test fixture's labelled cases. The second also indexes the
real directory the build wrote (never committed) and times 1,000 listings made
from its own names; it reports speed only, since real listings have no labels.
"""

import argparse
import random
import sys
import time
from collections.abc import Callable, Iterable
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from match import handmade, synthetic
from snowlight.match import (
    Directory,
    Matcher,
    MatchResult,
    MatchSettings,
    load_directory,
    normalize,
)


def _say(text: str) -> None:
    sys.stdout.write(text + "\n")


_REPEATS = 3
"""Cold runs of each timed step: the machine's CPUs are shared, so the fastest counts."""


def _repeated[T](work: Callable[[], T]) -> tuple[T, list[float]]:
    """Run ``work`` :data:`_REPEATS` times, each from empty normalization caches.

    Returns the last run's result and every run's seconds.
    """
    seconds: list[float] = []

    def once() -> T:
        normalize.clear_caches()
        started = time.perf_counter()
        result = work()
        seconds.append(time.perf_counter() - started)
        return result

    for _ in range(_REPEATS - 1):
        once()
    return once(), seconds


def _runs(seconds: list[float], digits: int) -> str:
    """``"2.71 s (fastest of 2.71, 3.02, 2.95)"``."""
    each = ", ".join(f"{s:.{digits}f}" for s in seconds)
    return f"{min(seconds):.{digits}f} s (fastest of {each})"


def _synthetic(listings: int) -> None:
    started = time.perf_counter()
    records = synthetic.build_directory(districts_per_state=340, private_per_state=273, seed=7)
    cases = synthetic.build_cases(records, count=listings, seed=11)
    generated = time.perf_counter() - started
    distinct = len({item.record.name for item in records})
    _say(f"synthetic: {len(records):,} records ({distinct:,} distinct names), {generated:.2f} s")

    matcher, builds = _repeated(lambda: Matcher(Directory(item.record for item in records)))
    _say(f"  index build: {_runs(builds, 2)}")

    def match_all() -> list[MatchResult]:
        return [
            matcher.match(
                case.listing,
                states=case.states,
                counties=case.counties,
                near=case.near,
                category=case.category,
            )
            for case in cases
        ]

    # Later runs reuse the lookups the first made (each state's towns and
    # vocabulary, read on first use); the first run is the cold one.
    results, matches = _repeated(match_all)
    _say(f"  match {listings:,} listings: {_runs(matches, 3)}, the first cold")

    tp, fp, positives = _count(zip(cases, results, strict=True))
    precision = tp / (tp + fp) if tp + fp else 1.0
    _say(f"  precision {precision:.4f}, recall {tp / positives:.4f} ({positives} positives)")


def _count(runs: Iterable[tuple[synthetic.Case, MatchResult]]) -> tuple[int, int, int]:
    """True positives, false positives and positives: a system's listing names all its districts."""
    tp = fp = positives = 0
    for case, result in runs:
        got = frozenset(record.id for record in result.targets)
        positives += case.expected is not None
        tp += bool(got) and got == case.targets
        fp += bool(got) and got != case.targets
    return tp, fp, positives


def _sweep() -> None:
    """Precision and recall on the test fixture at a range of thresholds."""
    background = synthetic.build_directory(districts_per_state=40, private_per_state=20, seed=2026)
    generated = synthetic.build_cases(background, count=3000, seed=20260925)
    with_hand = Matcher(Directory([*handmade.RECORDS, *(item.record for item in background)]))
    alone = Matcher(Directory(item.record for item in background))
    runs = [(with_hand, case) for case in handmade.CASES] + [(alone, case) for case in generated]
    _say("threshold sweep (hand-written and generated cases):")
    _say("  threshold  precision  recall   accepted")
    for threshold in (0.70, 0.75, 0.80, 0.85, 0.90, 0.95):
        outcomes: list[tuple[synthetic.Case, MatchResult]] = []
        for matcher, case in runs:
            matcher.settings = MatchSettings(threshold=threshold)
            result = matcher.match(
                case.listing,
                states=case.states,
                counties=case.counties,
                near=case.near,
                category=case.category,
            )
            outcomes.append((case, result))
        tp, fp, positives = _count(outcomes)
        precision = tp / (tp + fp) if tp + fp else 1.0
        _say(f"  {threshold:9.2f}  {precision:9.4f}  {tp / positives:6.4f}  {tp + fp:8d}")


def _real(folder: Path, listings: int) -> None:
    started = time.perf_counter()
    directory = load_directory(folder)
    _say(f"real: {len(directory):,} records loaded in {time.perf_counter() - started:.2f} s")
    started = time.perf_counter()
    matcher = Matcher(directory)
    _say(f"  index build: {time.perf_counter() - started:.2f} s")
    rng = random.Random(3)  # noqa: S311 - sampling, not cryptography
    sample = rng.sample(list(directory), listings)
    started = time.perf_counter()
    accepted = sum(
        matcher.match(record.name.upper(), states=[record.state]).accepted for record in sample
    )
    elapsed = time.perf_counter() - started
    _say(f"  match {listings:,} names (statewide, upper-cased): {elapsed:.3f} s")
    _say(f"  accepted {accepted:,}; the rest share a name with another record in the state")


def main() -> None:
    """Run the benchmark."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--directory", type=Path, help="internal directory folder of a build")
    parser.add_argument("--listings", type=int, default=1000)
    args = parser.parse_args()
    _synthetic(args.listings)
    _sweep()
    if args.directory is not None:
        _real(args.directory, args.listings)


if __name__ == "__main__":
    main()
