#!/usr/bin/env node
// @ts-check
/**
 * Generates TypeScript types for the published data files from ../schemas.
 *
 *   node scripts/gen-types.mjs            write src/types/generated/
 *   node scripts/gen-types.mjs --check    change nothing; exit 1 if it is stale
 *
 * Input: every ../schemas/*.schema.json (JSON Schema 2020-12, written by
 * `uv run python -m snowlight.schemas` in pipeline/) and ../schemas/fingerprint.json.
 *
 * Output, in src/types/generated/:
 *
 *   index.ts        an interface per object, a type per named value, a const
 *                   table per integer code (Status.closed === 0), PUBLISHED_PATHS
 *                   and the PublishedDocuments map from file to type.
 *   fingerprint.ts  the schemas' fingerprint, typed against schemas/fingerprint.json,
 *                   so `npm run check` fails once the schemas change until this
 *                   script runs again.
 *
 * The output is a pure function of the schema files: no dates, no absolute paths,
 * sorted everywhere, and already in Prettier's format for this repository's
 * settings. Only Node's standard library is used, so the pipeline's tests can run
 * `--check` without installing the web dependencies.
 *
 * The translation covers exactly the JSON Schema that pydantic writes for these
 * models and throws on anything else, rather than guessing a type.
 */
import { createHash } from 'node:crypto';
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const WEB = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SCHEMA_DIR = resolve(WEB, '../schemas');
const OUT_DIR = resolve(WEB, 'src/types/generated');
const SCHEMA_SUFFIX = '.schema.json';
const FINGERPRINT_FILE = 'fingerprint.json';
const BANNER =
  '// Generated by web/scripts/gen-types.mjs from schemas/*.schema.json. Do not edit.\n' +
  '// Regenerate: `uv run python -m snowlight.schemas` in pipeline/, then `npm run gen:types`.\n';
const PRINT_WIDTH = 100;
const INDENT = '  ';

/** Keywords that only document or constrain a value; they do not change its type. */
const ANNOTATIONS = new Set([
  '$comment',
  'description',
  'exclusiveMaximum',
  'exclusiveMinimum',
  'format',
  'maxLength',
  'maximum',
  'minLength',
  'minimum',
  'pattern',
  'title',
  'uniqueItems',
]);

/** Keywords only a document's root has. */
const ROOT_ONLY = new Set(['$defs', '$schema', '$comment', 'x-snowlight-path']);

/** Constraint keywords worth repeating in a type's doc comment, in this order. */
const DOC_TAGS = [
  'format',
  'pattern',
  'minimum',
  'exclusiveMinimum',
  'maximum',
  'exclusiveMaximum',
  'minLength',
  'maxLength',
  'minItems',
  'maxItems',
];

class SchemaError extends Error {}

/**
 * @typedef {{ readonly [key: string]: unknown }} Schema
 * @typedef {{ file: string, name: string, root: Schema }} Document
 */

/**
 * @param {unknown} value
 * @param {string} where
 * @returns {Schema}
 */
function asSchema(value, where) {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new SchemaError(`${where}: expected a schema object`);
  }
  return /** @type {Schema} */ (value);
}

/**
 * @param {unknown} value
 * @param {string} where
 * @returns {Schema[]}
 */
function asSchemas(value, where) {
  if (!Array.isArray(value)) throw new SchemaError(`${where}: expected a list of schemas`);
  return value.map((item, i) => asSchema(item, `${where}[${String(i)}]`));
}

/**
 * @param {unknown} value
 * @param {string} where
 * @returns {string[]}
 */
function asStrings(value, where) {
  if (!Array.isArray(value) || !value.every((item) => typeof item === 'string')) {
    throw new SchemaError(`${where}: expected a list of strings`);
  }
  return /** @type {string[]} */ (value);
}

/** @param {Buffer} data */
function sha256(data) {
  return createHash('sha256').update(data).digest('hex');
}

/**
 * The fingerprint of the schema files, as pipeline/snowlight/schemas/export.py computes it:
 * for each schema file in name order, its name, a newline, its sha256 and a newline.
 * @param {Map<string, Buffer>} files
 */
export function fingerprint(files) {
  const digest = createHash('sha256');
  for (const [name, data] of [...files].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))) {
    if (name.endsWith(SCHEMA_SUFFIX)) digest.update(`${name}\n${sha256(data)}\n`);
  }
  return digest.digest('hex');
}

/**
 * @param {string} dir
 * @returns {{ documents: Document[], fingerprint: string }}
 */
function readSchemas(dir) {
  if (!existsSync(dir)) throw new SchemaError(`${dir} does not exist`);
  /** @type {Map<string, Buffer>} */
  const files = new Map();
  for (const name of readdirSync(dir).sort()) {
    if (name.endsWith(SCHEMA_SUFFIX)) files.set(name, readFileSync(join(dir, name)));
  }
  if (files.size === 0) throw new SchemaError(`no *${SCHEMA_SUFFIX} files in ${dir}`);
  const print = fingerprint(files);
  /** @type {unknown} */
  const recorded = JSON.parse(readFileSync(join(dir, FINGERPRINT_FILE), 'utf8'));
  const keys = Object.keys(asSchema(recorded, FINGERPRINT_FILE));
  if (keys.length !== 1 || keys[0] !== print) {
    throw new SchemaError(
      `${FINGERPRINT_FILE} does not match the schema files; ` +
        'rerun `uv run python -m snowlight.schemas` in pipeline/',
    );
  }
  const documents = [...files].map(([file, data]) => {
    /** @type {unknown} */
    const parsed = JSON.parse(data.toString('utf8'));
    const root = asSchema(parsed, file);
    if (typeof root.title !== 'string') throw new SchemaError(`${file}: the root has no title`);
    return { file, name: root.title, root };
  });
  return { documents, fingerprint: print };
}

/** Recursively key-sorted JSON, for comparing definitions. @param {unknown} value */
function canonical(value) {
  return JSON.stringify(value, (_key, /** @type {unknown} */ item) =>
    item !== null && typeof item === 'object' && !Array.isArray(item)
      ? Object.fromEntries(Object.entries(item).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)))
      : item,
  );
}

/** @param {string} text */
function quote(text) {
  return `'${text.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/** @param {unknown} value */
function literal(value) {
  if (typeof value === 'string') return quote(value);
  if (typeof value === 'number' || typeof value === 'boolean' || value === null) {
    return JSON.stringify(value);
  }
  throw new SchemaError(`cannot write ${JSON.stringify(value)} as a literal type`);
}

/** @param {string} name */
function isIdentifier(name) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name);
}

/**
 * @param {Schema} schema
 * @param {string[]} allowed
 * @param {string} where
 */
function allowOnly(schema, allowed, where) {
  for (const key of Object.keys(schema)) {
    if (!allowed.includes(key) && !ANNOTATIONS.has(key)) {
      throw new SchemaError(`${where}: unsupported keyword ${key}`);
    }
  }
}

/**
 * The TypeScript for a schema used in place (a property, an item, a union member).
 * @param {Schema} schema
 * @param {string} where
 * @param {Set<string>} names
 * @returns {string}
 */
function typeOf(schema, where, names) {
  if ('$ref' in schema) {
    allowOnly(schema, ['$ref'], where);
    const match = /^#\/\$defs\/([A-Za-z][A-Za-z0-9]*)$/.exec(String(schema.$ref));
    if (!match?.[1] || !names.has(match[1])) {
      throw new SchemaError(`${where}: unknown reference ${String(schema.$ref)}`);
    }
    return match[1];
  }
  if ('const' in schema) {
    allowOnly(schema, ['const', 'type'], where);
    return literal(schema.const);
  }
  if ('enum' in schema) {
    allowOnly(schema, ['enum', 'type', 'x-enum-names'], where);
    if (!Array.isArray(schema.enum)) throw new SchemaError(`${where}: enum is not a list`);
    return schema.enum.map(literal).join(' | ');
  }
  for (const key of ['anyOf', 'oneOf']) {
    if (key in schema) {
      allowOnly(schema, [key, 'discriminator'], where);
      const members = asSchemas(schema[key], `${where}.${key}`);
      const types = members.map((member, i) =>
        typeOf(member, `${where}.${key}[${String(i)}]`, names),
      );
      const unique = [...new Set(types)];
      const ordered = [
        ...unique.filter((t) => t !== 'null'),
        ...unique.filter((t) => t === 'null'),
      ];
      return ordered.join(' | ');
    }
  }
  switch (schema.type) {
    case 'string':
      allowOnly(schema, ['type'], where);
      return 'string';
    case 'integer':
    case 'number':
      allowOnly(schema, ['type'], where);
      return 'number';
    case 'boolean':
      allowOnly(schema, ['type'], where);
      return 'boolean';
    case 'null':
      allowOnly(schema, ['type'], where);
      return 'null';
    case 'array':
      return arrayType(schema, where, names);
    default:
      throw new SchemaError(`${where}: cannot translate ${canonical(schema)}`);
  }
}

/**
 * @param {Schema} schema
 * @param {string} where
 * @param {Set<string>} names
 */
function arrayType(schema, where, names) {
  if ('prefixItems' in schema) {
    allowOnly(schema, ['type', 'prefixItems', 'minItems', 'maxItems', 'items'], where);
    const items = asSchemas(schema.prefixItems, `${where}.prefixItems`);
    if (schema.minItems !== items.length || schema.maxItems !== items.length) {
      throw new SchemaError(`${where}: only fixed-length tuples are supported`);
    }
    if ('items' in schema && schema.items !== false) {
      throw new SchemaError(`${where}: tuples with rest items are not supported`);
    }
    const members = items.map((item, i) => {
      const type = typeOf(item, `${where}.prefixItems[${String(i)}]`, names);
      if (typeof item.title !== 'string') return type;
      if (!isIdentifier(item.title)) throw new SchemaError(`${where}: bad label ${item.title}`);
      return `${item.title}: ${type}`;
    });
    if (members.some((m) => m.includes(':')) && !members.every((m) => m.includes(':'))) {
      throw new SchemaError(`${where}: label every tuple position or none`);
    }
    return `readonly [${members.join(', ')}]`;
  }
  allowOnly(schema, ['type', 'items', 'minItems', 'maxItems'], where);
  const item = typeOf(asSchema(schema.items, `${where}.items`), `${where}.items`, names);
  const simple = /^[A-Za-z0-9_$]+$/.test(item);
  return `readonly ${simple ? item : `(${item})`}[]`;
}

/**
 * Word-wraps text into doc comment lines at the given indent.
 * @param {string} text
 * @param {string} indent
 */
function docLines(text, indent) {
  const width = PRINT_WIDTH - indent.length - 3;
  /** @type {string[]} */
  const lines = [];
  for (const paragraph of text.replace(/\*\//g, '*\\/').split('\n')) {
    if (paragraph.trim() === '') {
      lines.push('');
      continue;
    }
    let line = '';
    for (const word of paragraph.trim().split(/\s+/)) {
      if (line && line.length + 1 + word.length > width) {
        lines.push(line);
        line = word;
      } else {
        line = line ? `${line} ${word}` : word;
      }
    }
    lines.push(line);
  }
  while (lines.at(-1) === '') lines.pop();
  return lines;
}

/**
 * The doc comment for a declaration or property, or '' when there is nothing to say.
 * @param {Schema} schema
 * @param {string} indent
 * @param {boolean} withTags
 */
function docComment(schema, indent, withTags) {
  const lines = typeof schema.description === 'string' ? docLines(schema.description, indent) : [];
  if (withTags) {
    for (const tag of DOC_TAGS) {
      const value = schema[tag];
      if (typeof value === 'string' || typeof value === 'number') {
        lines.push(`@${tag} ${String(value)}`.replace(/\*\//g, '*\\/'));
      }
    }
  }
  const [only, ...rest] = lines;
  if (only === undefined) return '';
  if (rest.length === 0 && indent.length + 7 + only.length <= PRINT_WIDTH) {
    return `${indent}/** ${only} */\n`;
  }
  const body = lines.map((line) => `${indent} *${line ? ` ${line}` : ''}`).join('\n');
  return `${indent}/**\n${body}\n${indent} */\n`;
}

/**
 * Splits on a separator that is not inside brackets or parentheses.
 * @param {string} text
 * @param {string} separator
 */
function splitTopLevel(text, separator) {
  /** @type {string[]} */
  const parts = [];
  let depth = 0;
  let start = 0;
  for (let i = 0; i < text.length; i += 1) {
    const char = text.charAt(i);
    if (char === '[' || char === '(' || char === '{') depth += 1;
    else if (char === ']' || char === ')' || char === '}') depth -= 1;
    else if (depth === 0 && text.startsWith(separator, i)) {
      parts.push(text.slice(start, i));
      start = i + separator.length;
      i += separator.length - 1;
    }
  }
  parts.push(text.slice(start));
  return parts;
}

/**
 * `export type Name = value;`, broken the way Prettier breaks it when it is too long.
 * @param {string} name
 * @param {string} value
 */
function typeAlias(name, value) {
  const line = `export type ${name} = ${value};`;
  if (line.length <= PRINT_WIDTH) return `${line}\n`;
  const tuple = /^readonly \[(.*)\]$/.exec(value);
  if (tuple?.[1] !== undefined) {
    const members = splitTopLevel(tuple[1], ', ').map((member) => `${INDENT}${member},\n`);
    return `export type ${name} = readonly [\n${members.join('')}];\n`;
  }
  const members = splitTopLevel(value, ' | ');
  if (members.length > 1) {
    return `export type ${name} =\n${members.map((m) => `${INDENT}| ${m}`).join('\n')};\n`;
  }
  throw new SchemaError(`${name}: its type does not fit on one line: ${value}`);
}

/**
 * @param {string} name
 * @param {Schema} schema
 * @param {Set<string>} names
 */
function interfaceDeclaration(name, schema, names) {
  allowOnly(schema, ['type', 'properties', 'required', 'additionalProperties'], name);
  if (schema.additionalProperties !== false) {
    throw new SchemaError(`${name}: objects must forbid additional properties`);
  }
  const properties = asSchema(schema.properties ?? {}, `${name}.properties`);
  const required = asStrings(schema.required ?? [], `${name}.required`);
  const optional = Object.keys(properties)
    .filter((key) => !required.includes(key))
    .sort();
  const members = [...required, ...optional].map((key) => {
    if (!(key in properties)) throw new SchemaError(`${name}: ${key} is required but undefined`);
    if (!isIdentifier(key)) throw new SchemaError(`${name}: property ${key} is not an identifier`);
    const property = asSchema(properties[key], `${name}.${key}`);
    const type = typeOf(property, `${name}.${key}`, names);
    const line = `${INDENT}readonly ${key}${required.includes(key) ? '' : '?'}: ${type};`;
    if (line.length > PRINT_WIDTH) {
      throw new SchemaError(`${name}.${key}: name the type; ${line.trim()} is too long`);
    }
    return `${docComment(property, INDENT, false)}${line}\n`;
  });
  return `${docComment(schema, '', false)}export interface ${name} {\n${members.join('')}}\n`;
}

/**
 * @param {string} name
 * @param {Schema} schema
 */
function codeTable(name, schema) {
  allowOnly(schema, ['type', 'enum', 'x-enum-names'], name);
  const labels = asStrings(schema['x-enum-names'], `${name}.x-enum-names`);
  const values = schema.enum;
  if (!Array.isArray(values) || labels.length !== values.length) {
    throw new SchemaError(`${name}: x-enum-names does not match enum`);
  }
  const rows = labels.map((label, i) => {
    if (!isIdentifier(label)) throw new SchemaError(`${name}: bad enum name ${label}`);
    return `${INDENT}${label}: ${literal(values[i])},\n`;
  });
  const doc = docComment(schema, '', false);
  return (
    `${doc}export const ${name} = {\n${rows.join('')}} as const;\n` +
    `${doc}export type ${name} = (typeof ${name})[keyof typeof ${name}];\n`
  );
}

/**
 * The declaration of one named schema.
 * @param {string} name
 * @param {Schema} schema
 * @param {Set<string>} names
 */
function declaration(name, schema, names) {
  if (schema.type === 'object') return interfaceDeclaration(name, schema, names);
  if ('x-enum-names' in schema) return codeTable(name, schema);
  return `${docComment(schema, '', true)}${typeAlias(name, typeOf(schema, name, names))}`;
}

/** @param {string} file */
function camelKey(file) {
  return file
    .slice(0, -SCHEMA_SUFFIX.length)
    .replace(/-([a-z0-9])/g, (_match, /** @type {string} */ char) => char.toUpperCase());
}

/**
 * Every generated file, by name.
 * @param {Document[]} documents
 * @param {string} print
 * @returns {Map<string, string>}
 */
export function generate(documents, print) {
  /** @type {Map<string, { schema: Schema, users: Set<string> }>} */
  const definitions = new Map();
  for (const { file, name, root } of documents) {
    const body = Object.fromEntries(Object.entries(root).filter(([key]) => !ROOT_ONLY.has(key)));
    const defs = Object.entries(asSchema(root.$defs ?? {}, `${file}.$defs`));
    /** @type {[string, unknown][]} */
    const named = [...defs, [name, body]];
    for (const [key, value] of named) {
      if (!isIdentifier(key)) throw new SchemaError(`${file}: ${key} is not an identifier`);
      const schema = asSchema(value, `${file}: ${key}`);
      const seen = definitions.get(key);
      if (seen === undefined) {
        definitions.set(key, { schema, users: new Set([file]) });
      } else if (canonical(seen.schema) === canonical(schema)) {
        seen.users.add(file);
      } else {
        const first = [...seen.users].join(', ');
        throw new SchemaError(`${key} is defined differently in ${first} and ${file}`);
      }
    }
  }
  const names = new Set(definitions.keys());
  const roots = new Set(documents.map((d) => d.name));
  /** @param {string} key */
  const declare = (key) => {
    const found = definitions.get(key);
    if (found === undefined) throw new SchemaError(`${key} is not defined`);
    return `\n${declaration(key, found.schema, names)}`;
  };

  let out = BANNER;
  out +=
    '\n/** Where the site serves each published file, under its data root. {id} is a replay id. */\n';
  out += 'export const PUBLISHED_PATHS = {\n';
  for (const { file, root } of documents) {
    const path = root['x-snowlight-path'];
    if (typeof path !== 'string') throw new SchemaError(`${file}: no x-snowlight-path`);
    out += `${INDENT}${camelKey(file)}: ${quote(path)},\n`;
  }
  out += '} as const;\n';
  out += '\n/** The type of each published file, by its key in PUBLISHED_PATHS. */\n';
  out += 'export interface PublishedDocuments {\n';
  for (const { file, name } of documents) out += `${INDENT}readonly ${camelKey(file)}: ${name};\n`;
  out += '}\n';

  const shared = [...definitions]
    .filter(([key, def]) => def.users.size > 1 && !roots.has(key))
    .map(([key]) => key)
    .sort();
  if (shared.length > 0) {
    out +=
      '\n// Shared by several files ---------------------------------------------------------\n';
    for (const key of shared) out += declare(key);
  }
  for (const { file, name } of documents) {
    out += `\n${`// ${file.slice(0, -SCHEMA_SUFFIX.length)} `.padEnd(PRINT_WIDTH - 17, '-')}\n`;
    const own = [...definitions]
      .filter(([key, def]) => key !== name && def.users.size === 1 && def.users.has(file))
      .map(([key]) => key)
      .sort();
    for (const key of [name, ...own]) out += declare(key);
  }

  const check =
    `${BANNER}\n` +
    "import type fingerprint from '../../../../schemas/fingerprint.json';\n\n" +
    '/**\n' +
    ' * The fingerprint of the schemas these types were generated from. When schemas/ changes,\n' +
    ' * its fingerprint.json gets a new key and this line stops type-checking until\n' +
    ' * `npm run gen:types` runs again.\n' +
    ' */\n' +
    'export const SCHEMAS_FINGERPRINT: keyof typeof fingerprint =\n' +
    `${INDENT}${quote(print)};\n`;

  return new Map([
    ['fingerprint.ts', check],
    ['index.ts', out],
  ]);
}

/**
 * Generated files in the output folder that this run would not write (left over from an
 * older run); hand-written files there do not start with the banner and are left alone.
 * @param {Map<string, string>} outputs
 */
function leftovers(outputs) {
  if (!existsSync(OUT_DIR)) return [];
  return readdirSync(OUT_DIR)
    .filter((name) => name.endsWith('.ts') && !outputs.has(name))
    .filter((name) => readFileSync(join(OUT_DIR, name), 'utf8').startsWith(BANNER));
}

function main() {
  const args = process.argv.slice(2);
  const unknown = args.filter((arg) => arg !== '--check');
  if (unknown.length > 0) {
    process.stderr.write(
      `unknown arguments: ${unknown.join(' ')}\nusage: gen-types.mjs [--check]\n`,
    );
    return 2;
  }
  const checkOnly = args.includes('--check');
  const { documents, fingerprint: print } = readSchemas(SCHEMA_DIR);
  const outputs = generate(documents, print);
  const stale = [...outputs]
    .filter(([name, text]) => {
      const path = join(OUT_DIR, name);
      return !existsSync(path) || readFileSync(path, 'utf8') !== text;
    })
    .map(([name]) => name);
  const extra = leftovers(outputs);
  const shown = (/** @type {string} */ name) => relative(process.cwd(), join(OUT_DIR, name));
  if (checkOnly) {
    for (const name of [...stale, ...extra]) process.stderr.write(`stale: ${shown(name)}\n`);
    if (stale.length + extra.length > 0) {
      process.stderr.write('run: npm run gen:types\n');
      return 1;
    }
    return 0;
  }
  mkdirSync(OUT_DIR, { recursive: true });
  for (const [name, text] of outputs) {
    if (!stale.includes(name)) continue;
    writeFileSync(join(OUT_DIR, name), text);
    process.stdout.write(`wrote ${shown(name)}\n`);
  }
  for (const name of extra) {
    unlinkSync(join(OUT_DIR, name));
    process.stdout.write(`removed ${shown(name)}\n`);
  }
  return 0;
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    process.exitCode = main();
  } catch (error) {
    if (!(error instanceof SchemaError)) throw error;
    process.stderr.write(`gen-types: ${error.message}\n`);
    process.exitCode = 1;
  }
}
