"""Given names, for telling a person's forename in a school's name from a place's word.

A school named for a person is written with the person's forenames
(``"John F Kennedy Middle School"``), their initials (``"J F Kennedy Middle
School"``) or neither (``"Kennedy Middle"``), and a list may leave them out
(``"Kennedy Middle School"``): see :func:`snowlight.match.normalize.forenames`.
Initials say plainly that a person's name follows; a spelled forename without
one (``"Charles White Elementary"``) is told from a place's word
(``"Oak Park Elementary"``) only by whether it is a given name.

:data:`GIVEN_NAMES` holds every first name of the U.S. Census Bureau's 1990
name files that at least 0.01 percent of the enumerated men or of the
enumerated women bore, lower case: ``dist.male.first`` (1,219 names) and
``dist.female.first`` (4,275 names), published at
https://www2.census.gov/topics/genealogy/1990surnames/ (SHA-256
``0a5078ef6effe3b483d15b0f7f95047662126c9bfb624ecd5e5b978fc0f2470b`` and
``bd2f310fc4e5d5e5ea122c9d4342c9821145823118eb20db1647f305ec77b358``), 1,555 names in all. Many
are place words too (``"Grace"``, ``"Rose"``, ``"Glen"``), which is why a
forename known only from this list, with no initial beside it, is never enough
to take a school on its surname alone (see
:mod:`snowlight.match.index`).
"""

from typing import Final

GIVEN_NAMES: Final[frozenset[str]] = frozenset(
    {
        "aaron", "abby", "abel", "abigail", "abraham", "ada", "adam", "addie", "adela", "adele",
        "adeline", "adolfo", "adolph", "adrian", "adriana", "adrienne", "agnes", "agustin", "aida",
        "aileen", "aimee", "al", "alan", "alana", "albert", "alberta", "alberto", "alejandra",
        "alejandro", "alex", "alexander", "alexandra", "alexandria", "alexis", "alfonso", "alfred",
        "alfredo", "ali", "alice", "alicia", "aline", "alisa", "alisha", "alison", "alissa",
        "allan", "allen", "allie", "allison", "allyson", "alma", "alonzo", "alphonso", "alta",
        "althea", "alton", "alvaro", "alvin", "alyce", "alyssa", "amalia", "amanda", "amber",
        "amelia", "amie", "amos", "amy", "ana", "anastasia", "andre", "andrea", "andres", "andrew",
        "andy", "angel", "angela", "angelia", "angelica", "angelina", "angeline", "angelo", "angie",
        "anita", "ann", "anna", "annabelle", "anne", "annette", "annie", "anthony", "antoine",
        "antoinette", "anton", "antonia", "antonio", "april", "araceli", "archie", "arlene",
        "arline", "armand", "armando", "arnold", "arthur", "arturo", "ashlee", "ashley", "aubrey",
        "audra", "audrey", "august", "augusta", "aurelia", "aurora", "austin", "autumn", "ava",
        "avery", "avis",
        "barbara", "barbra", "barry", "bart", "basil", "beatrice", "beatriz", "becky", "belinda",
        "ben", "benita", "benito", "benjamin", "bennie", "benny", "bernadette", "bernadine",
        "bernard", "bernardo", "bernice", "bert", "berta", "bertha", "bessie", "beth", "bethany",
        "betsy", "bette", "bettie", "betty", "bettye", "beulah", "beverly", "bianca", "bill",
        "billie", "billy", "blaine", "blake", "blanca", "blanche", "bob", "bobbi", "bobbie",
        "bobby", "bonita", "bonnie", "boyd", "brad", "bradford", "bradley", "brady", "brain",
        "brandi", "brandon", "brandy", "brenda", "brendan", "brent", "bret", "brett", "brian",
        "briana", "brianna", "bridget", "bridgette", "brittany", "brittney", "brooke", "bruce",
        "bruno", "bryan", "bryant", "bryce", "bryon", "buddy", "burton", "byron",
        "caitlin", "caleb", "callie", "calvin", "cameron", "camille", "candace", "candice", "candy",
        "cara", "carey", "carl", "carla", "carlene", "carlos", "carlton", "carly", "carmela",
        "carmella", "carmen", "carol", "carole", "carolina", "caroline", "carolyn", "carrie",
        "carroll", "cary", "casey", "cassandra", "cassie", "catalina", "catherine", "cathleen",
        "cathy", "cecelia", "cecil", "cecile", "cecilia", "cedric", "celeste", "celia", "cesar",
        "chad", "chandra", "charity", "charlene", "charles", "charlie", "charlotte", "charmaine",
        "chase", "chasity", "chelsea", "cheri", "cherie", "cheryl", "chester", "chris", "christa",
        "christi", "christian", "christie", "christina", "christine", "christopher", "christy",
        "chrystal", "chuck", "cindy", "claire", "clara", "clare", "clarence", "clarice", "clarissa",
        "clark", "claude", "claudette", "claudia", "claudine", "clay", "clayton", "clement", "cleo",
        "cleveland", "cliff", "clifford", "clifton", "clint", "clinton", "clyde", "cody", "cole",
        "colette", "colin", "colleen", "concepcion", "connie", "conrad", "constance", "consuelo",
        "cora", "corey", "corina", "corine", "corinne", "cornelia", "cornelius", "corrine", "cory",
        "courtney", "coy", "craig", "cristina", "crystal", "curt", "curtis", "cynthia",
        "daisy", "dale", "dallas", "damian", "damien", "damon", "dan", "dana", "dane", "daniel",
        "danielle", "danny", "dante", "daphne", "darcy", "darin", "darius", "darla", "darlene",
        "darnell", "darrel", "darrell", "darren", "darrin", "darryl", "darwin", "daryl", "dave",
        "david", "davis", "dawn", "dean", "deana", "deanna", "deanne", "debbie", "debora",
        "deborah", "debra", "dee", "deena", "deidre", "deirdre", "delbert", "delia", "della",
        "delores", "deloris", "demetrius", "dena", "denis", "denise", "dennis", "denny", "derek",
        "derick", "derrick", "desiree", "desmond", "devin", "devon", "dewayne", "dewey", "dexter",
        "diana", "diane", "dianna", "dianne", "diego", "dina", "dion", "dixie", "dollie", "dolly",
        "dolores", "domingo", "dominic", "dominick", "dominique", "don", "dona", "donald", "donna",
        "donnell", "donnie", "donovan", "dora", "doreen", "doris", "dorothea", "dorothy", "dorthy",
        "doug", "douglas", "doyle", "drew", "duane", "dustin", "dwayne", "dwight", "dylan",
        "earl", "earlene", "earline", "earnest", "earnestine", "ebony", "ed", "eddie", "eddy",
        "edgar", "edith", "edmond", "edmund", "edna", "eduardo", "edward", "edwin", "edwina",
        "effie", "efrain", "eileen", "elaine", "elbert", "eldon", "eleanor", "elena", "eli",
        "elias", "elijah", "elinor", "elisa", "elisabeth", "elise", "eliza", "elizabeth", "ella",
        "ellen", "elliot", "elliott", "ellis", "elma", "elmer", "elnora", "eloise", "elsa", "elsie",
        "elton", "elva", "elvia", "elvin", "elvira", "elvis", "elwood", "emanuel", "emery", "emil",
        "emilia", "emilio", "emily", "emma", "emmanuel", "emmett", "enrique", "eric", "erica",
        "erick", "ericka", "erik", "erika", "erin", "erma", "ernest", "ernestine", "ernesto",
        "ernie", "ervin", "erwin", "esmeralda", "esperanza", "essie", "esteban", "estela",
        "estella", "estelle", "ester", "esther", "ethan", "ethel", "etta", "eugene", "eugenia",
        "eula", "eunice", "eva", "evan", "evangeline", "eve", "evelyn", "everett",
        "fabian", "faith", "fannie", "fay", "faye", "federico", "felicia", "felipe", "felix",
        "fern", "fernando", "fidel", "flora", "florence", "flossie", "floyd", "forrest", "fran",
        "frances", "francine", "francis", "francisca", "francisco", "frank", "frankie", "franklin",
        "fred", "freda", "freddie", "freddy", "frederick", "fredrick", "frieda",
        "gabriel", "gabriela", "gabrielle", "gail", "gale", "garland", "garrett", "garry", "gary",
        "gavin", "gay", "gayle", "gena", "gene", "geneva", "genevieve", "geoffrey", "george",
        "georgette", "georgia", "georgina", "gerald", "geraldine", "gerard", "gerardo", "gerry",
        "gertrude", "gilbert", "gilberto", "gina", "ginger", "gladys", "glen", "glenda", "glenn",
        "glenna", "gloria", "goldie", "gonzalo", "gordon", "grace", "gracie", "graciela", "grady",
        "graham", "grant", "greg", "gregg", "gregorio", "gregory", "greta", "gretchen", "grover",
        "guadalupe", "guillermo", "gus", "gustavo", "guy", "gwen", "gwendolyn",
        "hal", "haley", "hannah", "hans", "harlan", "harley", "harold", "harriet", "harriett",
        "harrison", "harry", "harvey", "hattie", "hazel", "heath", "heather", "hector", "heidi",
        "helen", "helena", "helene", "henrietta", "henry", "herbert", "heriberto", "herman",
        "hilary", "hilda", "hillary", "hiram", "holly", "homer", "hope", "horace", "howard",
        "hubert", "hugh", "hugo", "humberto",
        "ian", "ida", "ignacio", "ila", "ilene", "imelda", "imogene", "ina", "inez", "ingrid",
        "ira", "irene", "iris", "irma", "irvin", "irving", "isaac", "isabel", "isabelle", "isaiah",
        "ismael", "israel", "issac", "iva", "ivan", "ivy",
        "jack", "jackie", "jackson", "jaclyn", "jacob", "jacqueline", "jacquelyn", "jaime", "jake",
        "jamal", "james", "jami", "jamie", "jan", "jana", "jane", "janelle", "janet", "janette",
        "janice", "janie", "janine", "janis", "janna", "jared", "jarrod", "jarvis", "jasmine",
        "jason", "jasper", "javier", "jay", "jayne", "jayson", "jean", "jeanette", "jeanie",
        "jeanine", "jeanne", "jeannette", "jeannie", "jeannine", "jeff", "jefferson", "jeffery",
        "jeffrey", "jeffry", "jenifer", "jenna", "jennie", "jennifer", "jenny", "jerald",
        "jeremiah", "jeremy", "jeri", "jermaine", "jerome", "jerri", "jerry", "jess", "jesse",
        "jessica", "jessie", "jesus", "jewel", "jewell", "jill", "jillian", "jim", "jimmie",
        "jimmy", "jo", "joan", "joann", "joanna", "joanne", "joaquin", "jocelyn", "jodi", "jodie",
        "jody", "joe", "joel", "joesph", "joey", "johanna", "john", "johnathan", "johnnie",
        "johnny", "jolene", "jon", "jonathan", "jonathon", "joni", "jordan", "jorge", "jose",
        "josefa", "josefina", "joseph", "josephine", "josh", "joshua", "josie", "joy", "joyce",
        "juan", "juana", "juanita", "judith", "judy", "julia", "julian", "juliana", "julianne",
        "julie", "juliette", "julio", "julius", "june", "junior", "justin", "justine",
        "kara", "karen", "kari", "karin", "karina", "karl", "karla", "kasey", "kate", "katelyn",
        "katharine", "katherine", "kathie", "kathleen", "kathrine", "kathryn", "kathy", "katie",
        "katrina", "katy", "kay", "kaye", "kayla", "keisha", "keith", "kelley", "kelli", "kellie",
        "kelly", "kelsey", "kelvin", "ken", "kendall", "kendra", "kendrick", "kenneth", "kenny",
        "kent", "kenya", "keri", "kermit", "kerri", "kerry", "kevin", "kim", "kimberley",
        "kimberly", "kirk", "kirsten", "kris", "krista", "kristen", "kristi", "kristie", "kristin",
        "kristina", "kristine", "kristopher", "kristy", "krystal", "kurt", "kyle",
        "lacey", "ladonna", "lakeisha", "lakisha", "lamar", "lamont", "lana", "lance", "lara",
        "larry", "latasha", "latisha", "latonya", "latoya", "laura", "laurel", "lauren", "laurence",
        "laurie", "laverne", "lavonne", "lawanda", "lawrence", "lea", "leah", "leann", "leanne",
        "lee", "leigh", "leila", "lela", "leland", "lena", "lenora", "lenore", "leo", "leola",
        "leon", "leona", "leonard", "leonardo", "leonor", "leroy", "lesley", "leslie", "lessie",
        "lester", "letha", "leticia", "levi", "lewis", "lidia", "lila", "lilia", "lilian",
        "liliana", "lillian", "lillie", "lilly", "lily", "lina", "linda", "lindsay", "lindsey",
        "lionel", "lisa", "liza", "lizzie", "lloyd", "logan", "lois", "lola", "lonnie", "lora",
        "loraine", "loren", "lorena", "lorene", "lorenzo", "loretta", "lori", "lorie", "lorna",
        "lorraine", "lorrie", "lottie", "lou", "louie", "louis", "louisa", "louise", "lourdes",
        "lowell", "loyd", "luann", "lucas", "lucia", "lucile", "lucille", "lucinda", "lucy",
        "luella", "luis", "luisa", "luke", "lula", "lupe", "luther", "luz", "lydia", "lyle",
        "lynda", "lynette", "lynn", "lynne", "lynnette",
        "mabel", "mable", "mack", "madeline", "madelyn", "madge", "mae", "magdalena", "maggie",
        "malcolm", "malinda", "mallory", "mamie", "mandy", "manuel", "manuela", "marc", "marcel",
        "marcella", "marci", "marcia", "marcie", "marco", "marcos", "marcus", "marcy", "margaret",
        "margarita", "margery", "margie", "margo", "margret", "marguerite", "mari", "maria",
        "marian", "marianne", "maribel", "maricela", "marie", "marietta", "marilyn", "marina",
        "mario", "marion", "marisa", "marisol", "marissa", "maritza", "marjorie", "mark", "marla",
        "marlene", "marlin", "marlon", "marsha", "marshall", "marta", "martha", "martin", "martina",
        "marty", "marva", "marvin", "mary", "maryann", "maryanne", "marylou", "mason", "mathew",
        "matilda", "matt", "matthew", "mattie", "maude", "maureen", "maurice", "mauricio", "mavis",
        "max", "maxine", "maxwell", "may", "maynard", "mayra", "meagan", "megan", "meghan",
        "melanie", "melba", "melinda", "melisa", "melissa", "melody", "melva", "melvin", "mercedes",
        "meredith", "merle", "mia", "micah", "michael", "micheal", "michel", "michele", "michelle",
        "mickey", "miguel", "mike", "milagros", "mildred", "miles", "millard", "millie", "milton",
        "mindy", "minerva", "minnie", "miranda", "miriam", "misty", "mitchell", "mitzi", "moises",
        "mollie", "molly", "mona", "monica", "monique", "monte", "monty", "morgan", "morris",
        "moses", "muriel", "murray", "myra", "myrna", "myron", "myrtle",
        "nadia", "nadine", "nancy", "nanette", "nannie", "naomi", "natalia", "natalie", "natasha",
        "nathan", "nathaniel", "neal", "ned", "neil", "nelda", "nell", "nellie", "nelson", "nettie",
        "neva", "nicholas", "nichole", "nick", "nickolas", "nicolas", "nicole", "nikki", "nina",
        "nita", "noah", "noe", "noel", "noemi", "nola", "nolan", "nona", "nora", "norbert",
        "noreen", "norma", "norman", "norris",
        "odell", "odessa", "ofelia", "ola", "olga", "olive", "oliver", "olivia", "ollie", "omar",
        "opal", "ophelia", "ora", "orlando", "orville", "oscar", "otis", "otto", "owen",
        "pablo", "paige", "pam", "pamela", "pat", "patrica", "patrice", "patricia", "patrick",
        "patsy", "patti", "patty", "paul", "paula", "paulette", "pauline", "pearl", "pearlie",
        "pedro", "peggy", "penelope", "penny", "percy", "perry", "pete", "peter", "petra", "phil",
        "philip", "phillip", "phyllis", "pierre", "polly", "preston", "priscilla",
        "quentin", "quincy", "quinton",
        "rachael", "rachel", "rachelle", "rae", "rafael", "ralph", "ramiro", "ramon", "ramona",
        "randal", "randall", "randi", "randolph", "randy", "raphael", "raquel", "raul", "ray",
        "raymond", "reba", "rebecca", "rebekah", "reed", "reggie", "regina", "reginald", "rena",
        "rene", "renee", "reuben", "reva", "rex", "reynaldo", "rhoda", "rhonda", "ricardo",
        "richard", "rick", "rickey", "rickie", "ricky", "rigoberto", "riley", "rita", "rob",
        "robbie", "robert", "roberta", "roberto", "robin", "robyn", "rocco", "rochelle", "rocky",
        "rod", "roderick", "rodger", "rodney", "rodolfo", "rodrigo", "rogelio", "roger", "roland",
        "rolando", "roman", "romeo", "ron", "ronald", "ronda", "ronnie", "roosevelt", "rory",
        "rosa", "rosalie", "rosalind", "rosalinda", "rosalyn", "rosanne", "rosario", "roscoe",
        "rose", "roseann", "rosella", "rosemarie", "rosemary", "rosetta", "rosie", "roslyn", "ross",
        "roxanne", "roxie", "roy", "royce", "ruben", "ruby", "rudolph", "rudy", "rufus", "russel",
        "russell", "rusty", "ruth", "ruthie", "ryan",
        "sabrina", "sadie", "sallie", "sally", "salvador", "salvatore", "sam", "samantha", "sammie",
        "sammy", "samuel", "sandra", "sandy", "santiago", "santos", "sara", "sarah", "sasha",
        "saul", "saundra", "savannah", "scot", "scott", "scotty", "sean", "sebastian", "selena",
        "selma", "serena", "sergio", "seth", "shana", "shane", "shanna", "shannon", "shari",
        "sharon", "sharron", "shaun", "shauna", "shawn", "shawna", "sheena", "sheila", "shelby",
        "sheldon", "shelia", "shelley", "shelly", "sheree", "sheri", "sherman", "sherri", "sherrie",
        "sherry", "sheryl", "shirley", "sidney", "silvia", "simon", "simone", "socorro", "sofia",
        "solomon", "son", "sondra", "sonia", "sonja", "sonya", "sophia", "sophie", "spencer",
        "stacey", "staci", "stacie", "stacy", "stan", "stanley", "stefanie", "stella", "stephan",
        "stephanie", "stephen", "sterling", "steve", "steven", "stewart", "stuart", "sue", "summer",
        "susan", "susana", "susanna", "susanne", "susie", "suzanne", "suzette", "sybil",
        "sylvester", "sylvia",
        "tabatha", "tabitha", "tamara", "tameka", "tami", "tamika", "tammi", "tammie", "tammy",
        "tania", "tanisha", "tanya", "tara", "tasha", "taylor", "ted", "teddy", "terence", "teresa",
        "teri", "terrance", "terrell", "terrence", "terri", "terrie", "terry", "tessa", "thaddeus",
        "thelma", "theodore", "theresa", "therese", "thomas", "thurman", "tia", "tiffany", "tim",
        "timmy", "timothy", "tina", "toby", "todd", "tom", "tomas", "tommie", "tommy", "toni",
        "tonia", "tony", "tonya", "tracey", "traci", "tracie", "tracy", "travis", "trent", "trevor",
        "tricia", "trina", "trisha", "troy", "trudy", "ty", "tyler", "tyrone", "tyson",
        "ulysses", "ursula",
        "valarie", "valeria", "valerie", "van", "vance", "vanessa", "vaughn", "velma", "vera",
        "vern", "verna", "vernon", "veronica", "vicente", "vicki", "vickie", "vicky", "victor",
        "victoria", "vilma", "vince", "vincent", "viola", "violet", "virgie", "virgil", "virginia",
        "vivian",
        "wade", "wallace", "walter", "wanda", "ward", "warren", "wayne", "wendell", "wendi",
        "wendy", "wesley", "whitney", "wilbert", "wilbur", "wiley", "wilfred", "wilfredo", "will",
        "willa", "willard", "william", "williams", "willie", "willis", "wilma", "wilson",
        "winifred", "winnie", "winston", "wm", "woodrow",
        "xavier",
        "yesenia", "yolanda", "young", "yvette", "yvonne",
        "zachary", "zelma",
    }
)  # fmt: skip
